name: hyperfiddle/electric
on:
  push:
    branches:
      - "**"
  pull_request:
jobs:
  jvm:
    name: Run JVM tests
    runs-on: [ubuntu-latest]
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2

    - run: git status

    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
         path: ~/.m2/repository
         key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
         restore-keys: |
           ${{ runner.os }}-maven-

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@3.4
      with:
        cli: 1.11.1.1113

    - name: prep
      run: clojure -A:test -P

    - name: Run tests
      run: ./ci/run_tests_jvm.sh

  browser:
    # if: ${{ false }} # Disabled until we fix the cljs test suite locally
    name: Run browser tests
    runs-on: [ubuntu-latest]
    timeout-minutes: 5
    steps:

    - uses: actions/checkout@v2

    - run: git status

    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
         path: ~/.m2/repository
         key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
         restore-keys: |
           ${{ runner.os }}-maven-

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@3.4
      with:
        cli: 1.11.1.1113

    - name: prep
      run: clojure -A:test -P

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.x

    - name: NPM install
      run: npm install --include=dev

    - name: Install Shadow
      run: npm install shadow-cljs

   
    # Install chrome and dependencies, puppeteer fails otherwise 
    - run: sudo apt-get update && sudo apt-get install -y wget gnupg
    - run: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    - run: sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    - run: sudo apt-get update && sudo apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 --no-install-recommends
    # - run: rm -rf /var/lib/apt/lists/*


    - name: Run Tests
      run: ./ci/run_tests_browser.sh

  nodejs:
    # if: ${{ false }}
    name: Run NodeJS tests
    runs-on: [ubuntu-latest]
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2

    - run: git status

    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
         path: ~/.m2/repository
         key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
         restore-keys: |
           ${{ runner.os }}-maven-

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@3.4
      with:
        cli: 1.11.1.1113

    - name: prep
      run: clojure -A:test -P

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.x

    - name: NPM install
      run: npm install

    - name: Install Shadow
      run: npm install shadow-cljs

    - name: Run Tests
      run: ./ci/run_tests_node.sh

  deploy:
    needs: [jvm, browser]
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: NO_COLOR=1 flyctl deploy --build-arg VERSION=$(git describe --tags --long) --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
